### ISSUE TITLE
chaine de connexion mongo  mongodb+srv non supportée

### ISSUE THREAD

**Issue by aindro** [VilledeMontreal/node-mongo#2]
Bonjour, notre DBA nous suggère d'utiliser une chaine de connexion mongo 'générique' avec mongodb+srv (mongodb+srv://db-name@server-name/?ssl=false&tls=false) au lieu de la chaine de connexion basique (mongodb://server-a:27001,server-b:27001,server-c:27001/db-name?replicaSet=rs-name).

J'essaie d'upgrader ma libraire à une version récente "@villemontreal/core-utils-mongo-nodejs-lib": "6.6.1".
Avec cette chaine de connexion générique mongodb+srv dans le fichier de configuration local.yaml (ou development.yaml), l'application ne peut pas se connecter à la BD tandis que avec la chaine de connexion basique, elle peut.
Cette chaine de connexion mongodb+srv peut être utiliser pour se connecter à la BD avec la commande mongo (sur shell) ou aussi par Studio3T sans problème.

Pourriez-vous voir si on supportera la chaine de connexion 'générique' mongodb+srv? Merci beaucoup

**Comment by psionikangel** [comment]
Dans un premier lieu, pour mettre à jour à la dernière version, il faut utiliser 
`"@villedemontreal/mongo":"6.7.1"` qui est le bon scope pour cette librairie-ci tel que publiée sur npmjs.org.

Ensuite, cette librairie utilise Mongoose pour initier la connexion avec MongoDB. Selon la documentation de la version 5.13.x de Mongoose (qui est la version utilisée en ce moment par notre librairie) la méthode de connexion avec une syntaxe d'URI mongodb+srv est supportée, mais pas dans la forme énoncée ci-haut.

Mongoose utilise à son tour la version 3.6 du Driver Node Mongo, qui documente la bonne syntaxe de connexion +srv ici:
https://www.mongodb.com/docs/drivers/node/v3.6/fundamentals/connection/connect/#connection-uri

![connexion](https://www.mongodb.com/docs/drivers/node/v3.6/includes/figures/connection-string-parts.png)

La méthode de connexion que vous désirez utiliser serait donc en théorie déjà supportée. Par contre, Il ne faut pas inclure le nom de la base de données dans l'URI. Il faut plutôt passer une clé/valeur `dbName` en tant qu'options à la méthode connect() de Mongoose ([Comme le mentionne la documentation ici](https://mongoosejs.com/docs/5.x/docs/connections.html#options)). Donc simplement rajouter le `dbName` dans l'objet d'options qui passe probablement déjà votre username/password devrait fonctionner.

En espérant que cette précision vous sera utile.
